# This docker-compose file is used to run the project's published image
#
# Usage: docker-compose up [-d]
#
# See comment in docker-compose.dev.yml if you want to run for development.

version: '3.4'

networks:
  reaction:
    external:
      name: reaction.localhost
  web:
    external:
      name: web

services:
  reaction-admin:
    image: reactioncommerce/admin:3.0.0-beta.7
    env_file:
      - ./.env
    networks:
      default:
      reaction:
      web:

    ports:
      - "4080:4080"
      - "9231:9229"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.entrypoints=http"
      - "traefik.http.routers.admin.rule=Host(`make.craflo.com`)"
      - "traefik.http.middlewares.admin-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.admin.middlewares=admin-https-redirect"
      - "traefik.http.routers.admin-secure.entrypoints=https"
      - "traefik.http.routers.admin-secure.rule=Host(`make.craflo.com`)"
      - "traefik.http.routers.admin-secure.tls=true"
      - "traefik.http.routers.admin-secure.service=admin"
      - "traefik.http.services.admin.loadbalancer.server.port=4080"
      - "traefik.docker.network=web"
    
