# This docker-compose file is used to run the project in Docker for development.
# The local files are mounted into the created container.
#
# Usage:
#  ln -s docker-compose.dev.yml docker-compose.override.yml
#  docker-compose up [-d]
#
# To go back to running the published image:
#  rm docker-compose.override.yml

version: '3.4'

networks:
  reaction:
    external:
      name: reaction.localhost

services:
  web:
    env_file:
      - .env
    image: reactioncommerce/node-dev:12.14.1-v1
    command: "./bin/start"
    networks:
      default:
      reaction:

    ports:
      - 902:2300

    volumes:
      - .:/usr/local/src/app
      - web-yarn:/home/node/.cache/yarn
      # Do not link in node_modules from the host
      # This allows IDEs to run lint etc with native add-ons for host OS
      # Without interfering with native add-ons in container
      - empty_node_modules:/usr/local/src/app/node_modules

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.entrypoints=http"
      - "traefik.http.routers.web.rule=Host(`pickbazar.craflo.com`)"
      - "traefik.http.middlewares.web-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.web.middlewares=web-https-redirect"
      - "traefik.http.routers.web-secure.entrypoints=https"
      - "traefik.http.routers.web-secure.rule=Host(`pickbazar.craflo.com`)"
      - "traefik.http.routers.web-secure.tls=true"
      - "traefik.http.routers.web-secure.service=web"
      - "traefik.http.services.web.loadbalancer.server.port=2300"
      - "traefik.docker.network=web"


volumes:
  web-yarn:
  empty_node_modules:
  api_empty_node_modules:
