# This docker-compose file is used to run the project in Docker for development.
# The local files are mounted into the created container.
#
# Usage:
#  ln -s docker-compose.yml docker-compose.override.yml
#  docker-compose up [-d]
#
# To go back to running the published image:
#  rm docker-compose.override.yml

version: '3.4'

networks:
  reaction:
    external:
      name: reaction.localhost
  web:
    external:
      name: web

services:
  web:
    image: reactioncommerce/node-dev:12.14.1-v1
    command: "./bin/start"
    volumes:
      - .:/usr/local/src/app
      - web-yarn:/home/node/.cache/yarn
      # Do not link in node_modules from the host
      # This allows IDEs to run lint etc with native add-ons for host OS
      # Without interfering with native add-ons in container
      - empty_node_modules:/usr/local/src/app/node_modules
    env_file:
      - ./.env
    
    networks:
      default:
      reaction:
      web:

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fe-prod.entrypoints=http"
      - "traefik.http.routers.fe-prod.rule=Host(`craflo.com`)"
      - "traefik.http.middlewares.fe-prod-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.fe-prod.middlewares=fe-prod-https-redirect"
      - "traefik.http.routers.fe-prod-secure.entrypoints=https"
      - "traefik.http.routers.fe-prod-secure.rule=Host(`craflo.com`)"
      - "traefik.http.routers.fe-prod-secure.tls=true"
      - "traefik.http.routers.fe-prod-secure.service=fe-prod"
      - "traefik.http.services.fe-prod.loadbalancer.server.port=4000"
      - "traefik.docker.network=web"

volumes:
  web-yarn:
  empty_node_modules:
  api_empty_node_modules:
